name: Build PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Update apt cache
      run: sudo apt-get update
  
    - name: Install dependencies
      run: sudo apt-get install -y sphinx texlive texlive-xetex texlive-fonts-extra latexmk

    - name: Build PDF
      run: make latexpdf

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: SNAC-PDF
        path: build/latex/SNAC.pdf