name: Continuous Deployment
description: Build the project and upload artifacts on push to master branch.

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 1 * *' # Runs on the first day of every month at midnight UTC

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build project
      uses: ./.github/actions/build
